import type { ToolbarCatalog } from '../../toolbar/types'
import {
  AlignCenterIcon,
  AlignJustifyIcon,
  AlignLeftIcon,
  AlignRightIcon,
  BoldIcon,
  BulletListIcon,
  ClearFormattingIcon,
  CustomCssIcon,
  FormatBrushIcon,
  FontColorIcon,
  FontFamilyIcon,
  FontPropertiesIcon,
  FontSizeIcon,
  HighlightColorIcon,
  ImageIcon,
  IndentIcon,
  ItalicIcon,
  NumberedListIcon,
  OutdentIcon,
  ParagraphPropertiesIcon,
  ParagraphStyleIcon,
  StrikethroughIcon,
  UnderlineIcon,
} from '../../icons'
import { FontColorSelect } from './FontColorSelect'
import { FontFamilySelect } from './FontFamilySelect'
import { FontSizeSelect } from './FontSizeSelect'
import { HighlightColorMenuPanel, HighlightColorSelect } from './HighlightColorSelect'
import { ParagraphStyleMenuPanel, ParagraphStyleSelect } from './ParagraphStyleSelect'

export const formatCatalog: ToolbarCatalog = {
  menus: {
    format: {
      id: 'format',
      labelKey: 'menuFormat',
      ariaKey: 'menuFormatAria',
    },
  },
  submenus: {
    paragraphStyles: {
      id: 'paragraphStyles',
      labelKey: 'menuParagraphStyles',
      ariaKey: 'menuParagraphStylesAria',
      panel: ParagraphStyleMenuPanel,
      enabled: 'isVisualMode',
    },
    font: {
      id: 'font',
      labelKey: 'menuFont',
      ariaKey: 'menuFontAria',
    },
    highlightColor: {
      id: 'highlightColor',
      labelKey: 'commandHighlightColor',
      ariaKey: 'commandHighlightColorAria',
      panel: HighlightColorMenuPanel,
      enabled: 'isVisualMode',
    },
    paragraph: {
      id: 'paragraph',
      labelKey: 'menuParagraph',
      ariaKey: 'menuParagraphAria',
    },
  },
  groups: {
    font: {
      id: 'font',
      labelKey: 'toolbarGroupFont',
    },
    align: {
      id: 'align',
      labelKey: 'toolbarGroupAlign',
    },
    paragraph: {
      id: 'paragraph',
      labelKey: 'toolbarGroupParagraph',
    },
  },
  items: {
    fontFamily: {
      id: 'fontFamily',
      widget: FontFamilySelect,
      icon: FontFamilyIcon,
      labelKey: 'commandFontFamily',
      ariaKey: 'commandFontFamilyAria',
      enabled: 'isVisualMode',
    },
    paragraphStyle: {
      id: 'paragraphStyle',
      widget: ParagraphStyleSelect,
      icon: ParagraphStyleIcon,
      labelKey: 'commandParagraphStyle',
      ariaKey: 'commandParagraphStyleAria',
      enabled: 'isVisualMode',
    },
    fontSize: {
      id: 'fontSize',
      widget: FontSizeSelect,
      icon: FontSizeIcon,
      labelKey: 'commandFontSize',
      ariaKey: 'commandFontSizeAria',
      enabled: 'isVisualMode',
    },
    fontProperties: {
      id: 'fontProperties',
      command: 'openFontProperties',
      icon: FontPropertiesIcon,
      labelKey: 'commandFontProperties',
      ariaKey: 'commandFontPropertiesAria',
      enabled: 'isVisualMode',
    },
    customCss: {
      id: 'customCss',
      command: 'openCustomCss',
      icon: CustomCssIcon,
      labelKey: 'commandCustomCss',
      ariaKey: 'commandCustomCssAria',
      enabled: 'isVisualMode',
    },
    paragraphProperties: {
      id: 'paragraphProperties',
      command: 'openParagraphProperties',
      icon: ParagraphPropertiesIcon,
      labelKey: 'commandParagraphProperties',
      ariaKey: 'commandParagraphPropertiesAria',
      enabled: 'isVisualMode',
    },
    imageProperties: {
      id: 'imageProperties',
      command: 'openImageProperties',
      icon: ImageIcon,
      labelKey: 'menuImage',
      ariaKey: 'menuImageAria',
      enabled: 'isImageSelected',
    },
    fontColor: {
      id: 'fontColor',
      widget: FontColorSelect,
      icon: FontColorIcon,
      labelKey: 'commandFontColor',
      ariaKey: 'commandFontColorAria',
      enabled: 'isVisualMode',
    },
    highlightColor: {
      id: 'highlightColor',
      widget: HighlightColorSelect,
      icon: HighlightColorIcon,
      labelKey: 'commandHighlightColor',
      ariaKey: 'commandHighlightColorAria',
      enabled: 'isVisualMode',
    },
    bold: {
      id: 'bold',
      command: 'toggleBold',
      icon: BoldIcon,
      labelKey: 'commandBold',
      ariaKey: 'commandBoldAria',
      active: 'isBold',
      enabled: 'isVisualMode',
      toggle: true,
    },
    italic: {
      id: 'italic',
      command: 'toggleItalic',
      icon: ItalicIcon,
      labelKey: 'commandItalic',
      ariaKey: 'commandItalicAria',
      active: 'isItalic',
      enabled: 'isVisualMode',
      toggle: true,
    },
    underline: {
      id: 'underline',
      command: 'toggleUnderline',
      icon: UnderlineIcon,
      labelKey: 'commandUnderline',
      ariaKey: 'commandUnderlineAria',
      active: 'isUnderline',
      enabled: 'isVisualMode',
      toggle: true,
    },
    strikethrough: {
      id: 'strikethrough',
      command: 'toggleStrikethrough',
      icon: StrikethroughIcon,
      labelKey: 'commandStrikethrough',
      ariaKey: 'commandStrikethroughAria',
      active: 'isStrikethrough',
      enabled: 'isVisualMode',
      toggle: true,
    },
    clearFormatting: {
      id: 'clearFormatting',
      command: 'clearFormatting',
      icon: ClearFormattingIcon,
      labelKey: 'commandClearFormatting',
      ariaKey: 'commandClearFormattingAria',
      enabled: 'hasTextSelection',
    },
    formatBrush: {
      id: 'formatBrush',
      command: 'toggleFormatBrush',
      icon: FormatBrushIcon,
      labelKey: 'commandFormatBrush',
      ariaKey: 'commandFormatBrushAria',
      active: 'isFormatBrushActive',
      enabled: 'isVisualMode',
      toggle: true,
    },
    alignLeft: {
      id: 'alignLeft',
      command: 'alignLeft',
      icon: AlignLeftIcon,
      labelKey: 'commandAlignLeft',
      ariaKey: 'commandAlignLeftAria',
      active: 'isAlignLeft',
      enabled: 'isVisualMode',
    },
    alignCenter: {
      id: 'alignCenter',
      command: 'alignCenter',
      icon: AlignCenterIcon,
      labelKey: 'commandAlignCenter',
      ariaKey: 'commandAlignCenterAria',
      active: 'isAlignCenter',
      enabled: 'isVisualMode',
    },
    alignRight: {
      id: 'alignRight',
      command: 'alignRight',
      icon: AlignRightIcon,
      labelKey: 'commandAlignRight',
      ariaKey: 'commandAlignRightAria',
      active: 'isAlignRight',
      enabled: 'isVisualMode',
    },
    alignJustify: {
      id: 'alignJustify',
      command: 'alignJustify',
      icon: AlignJustifyIcon,
      labelKey: 'commandAlignJustify',
      ariaKey: 'commandAlignJustifyAria',
      active: 'isAlignJustify',
      enabled: 'isVisualMode',
    },
    indent: {
      id: 'indent',
      command: 'indent',
      icon: IndentIcon,
      labelKey: 'commandIndent',
      ariaKey: 'commandIndentAria',
      enabled: 'isVisualMode',
    },
    outdent: {
      id: 'outdent',
      command: 'outdent',
      icon: OutdentIcon,
      labelKey: 'commandOutdent',
      ariaKey: 'commandOutdentAria',
      enabled: 'canOutdent',
    },
    bulletList: {
      id: 'bulletList',
      command: 'toggleBulletList',
      icon: BulletListIcon,
      labelKey: 'commandBulletList',
      ariaKey: 'commandBulletListAria',
      active: 'isBulletList',
      enabled: 'isVisualMode',
      toggle: true,
    },
    numberedList: {
      id: 'numberedList',
      command: 'toggleNumberedList',
      icon: NumberedListIcon,
      labelKey: 'commandNumberedList',
      ariaKey: 'commandNumberedListAria',
      active: 'isNumberedList',
      enabled: 'isVisualMode',
      toggle: true,
    },
  },
}
