import type { Meta, StoryObj } from '@storybook/react'
import { LocaleProvider } from '../../i18n/LocaleProvider'
import { ParagraphStyleSelect } from './ParagraphStyleSelect'

const meta = {
  title: 'Format/ParagraphStyleSelect',
  component: ParagraphStyleSelect,
  args: {
    commands: {
      save: async () => undefined,
      open: async () => undefined,
      print: () => undefined,
      undo: () => undefined,
      redo: () => undefined,
      setVisualMode: () => undefined,
      setHtmlMode: () => undefined,
      toggleFullscreen: () => undefined,
      openCustomizeToolbar: () => undefined,
      toggleBold: () => undefined,
      toggleItalic: () => undefined,
      toggleUnderline: () => undefined,
      toggleStrikethrough: () => undefined,
      setFontSize: () => undefined,
      setFontSizeUnit: () => undefined,
      setFontFamily: () => undefined,
      setFontColor: () => undefined,
      setHighlightColor: () => undefined,
      setParagraphStyle: () => undefined,
      alignLeft: () => undefined,
      alignCenter: () => undefined,
      alignRight: () => undefined,
      alignJustify: () => undefined,
      indent: () => undefined,
      outdent: () => undefined,
      toggleBulletList: () => undefined,
      toggleNumberedList: () => undefined,
      openFontProperties: () => undefined,
      applyFontProperties: () => undefined,
      openParagraphProperties: () => undefined,
      applyParagraphProperties: () => undefined,
      openPageProperties: () => undefined,
      applyPageProperties: () => undefined,
      openCustomParagraphStyleDialog: () => undefined,
      applyCustomParagraphStyle: () => undefined,
      openLinkDialog: () => undefined,
      applyLink: () => undefined,
      openBookmarkDialog: () => undefined,
      applyBookmark: () => undefined,
      openImageDialog: () => undefined,
      applyImage: () => undefined,
      openImageProperties: () => undefined,
      applyImageProperties: () => undefined,
      openTableDialog: () => undefined,
      applyTable: () => undefined,
      openTableProperties: () => undefined,
      applyTableProperties: () => undefined,
      openCellProperties: () => undefined,
      applyCellProperties: () => undefined,
      openRowProperties: () => undefined,
      applyRowProperties: () => undefined,
      insertRowBelow: () => undefined,
      insertRowBefore: () => undefined,
      deleteRow: () => undefined,
      insertColumnAfter: () => undefined,
      insertColumnBefore: () => undefined,
      deleteColumn: () => undefined,
      cut: async () => undefined,
      copy: async () => undefined,
      deleteSelection: () => undefined,
      clearFormatting: () => undefined,
    },
    queries: {
      isVisualMode: () => true,
      isHtmlMode: () => false,
      isFullscreen: () => false,
      canUndo: () => false,
      canRedo: () => false,
      isBold: () => false,
      isItalic: () => false,
      isUnderline: () => false,
      isStrikethrough: () => false,
      getFontSize: () => 12,
      getFontSizeUnit: () => 'pt' as const,
      isFontSizeMixed: () => false,
      getFontFamily: () => null,
      isFontFamilyMixed: () => false,
      getFontFaces: () => [],
      getFontColor: () => null,
      isFontColorMixed: () => false,
      getHighlightColor: () => null,
      isHighlightColorMixed: () => false,
      getParagraphStyle: () => 'p' as const,
      isParagraphStyleMixed: () => false,
      isAlignLeft: () => false,
      isAlignCenter: () => false,
      isAlignRight: () => false,
      isAlignJustify: () => false,
      canOutdent: () => false,
      isBulletList: () => false,
      isNumberedList: () => false,
      customParagraphStylesEnabled: () => false,
      getCustomParagraphStyles: () => [],
      isCustomParagraphStylesLoading: () => false,
      isLink: () => false,
      isImageSelected: () => false,
      isInTable: () => false,
      hasTextSelection: () => true,
    },
  },
  decorators: [
    (Story) => (
      <LocaleProvider>
        <div
          className="toolbar"
          style={{ display: 'flex', background: '#f0f0f0', padding: '0.25rem' }}
        >
          <Story />
        </div>
      </LocaleProvider>
    ),
  ],
} satisfies Meta<typeof ParagraphStyleSelect>

export default meta
type Story = StoryObj<typeof meta>

export const Default: Story = {}

export const Heading1: Story = {
  args: {
    queries: {
      isVisualMode: () => true,
      isHtmlMode: () => false,
      isFullscreen: () => false,
      canUndo: () => false,
      canRedo: () => false,
      isBold: () => false,
      isItalic: () => false,
      isUnderline: () => false,
      isStrikethrough: () => false,
      getFontSize: () => 12,
      getFontSizeUnit: () => 'pt' as const,
      isFontSizeMixed: () => false,
      getFontFamily: () => null,
      isFontFamilyMixed: () => false,
      getFontFaces: () => [],
      getFontColor: () => null,
      isFontColorMixed: () => false,
      getHighlightColor: () => null,
      isHighlightColorMixed: () => false,
      getParagraphStyle: () => 'h1' as const,
      isParagraphStyleMixed: () => false,
      isAlignLeft: () => false,
      isAlignCenter: () => false,
      isAlignRight: () => false,
      isAlignJustify: () => false,
      canOutdent: () => false,
      isBulletList: () => false,
      isNumberedList: () => false,
      customParagraphStylesEnabled: () => false,
      getCustomParagraphStyles: () => [],
      isCustomParagraphStylesLoading: () => false,
      isLink: () => false,
      isImageSelected: () => false,
      isInTable: () => false,
      hasTextSelection: () => true,
    },
  },
}

export const Mixed: Story = {
  args: {
    queries: {
      isVisualMode: () => true,
      isHtmlMode: () => false,
      isFullscreen: () => false,
      canUndo: () => false,
      canRedo: () => false,
      isBold: () => false,
      isItalic: () => false,
      isUnderline: () => false,
      isStrikethrough: () => false,
      getFontSize: () => 12,
      getFontSizeUnit: () => 'pt' as const,
      isFontSizeMixed: () => false,
      getFontFamily: () => null,
      isFontFamilyMixed: () => false,
      getFontFaces: () => [],
      getFontColor: () => null,
      isFontColorMixed: () => false,
      getHighlightColor: () => null,
      isHighlightColorMixed: () => false,
      getParagraphStyle: () => null,
      isParagraphStyleMixed: () => true,
      isAlignLeft: () => false,
      isAlignCenter: () => false,
      isAlignRight: () => false,
      isAlignJustify: () => false,
      canOutdent: () => false,
      isBulletList: () => false,
      isNumberedList: () => false,
      customParagraphStylesEnabled: () => false,
      getCustomParagraphStyles: () => [],
      isCustomParagraphStylesLoading: () => false,
      isLink: () => false,
      isImageSelected: () => false,
      isInTable: () => false,
      hasTextSelection: () => true,
    },
  },
}

export const Disabled: Story = {
  args: {
    disabled: true,
  },
}

export const CustomStyles: Story = {
  args: {
    queries: {
      isVisualMode: () => true,
      isHtmlMode: () => false,
      isFullscreen: () => false,
      canUndo: () => false,
      canRedo: () => false,
      isBold: () => false,
      isItalic: () => false,
      isUnderline: () => false,
      isStrikethrough: () => false,
      getFontSize: () => 12,
      getFontSizeUnit: () => 'pt' as const,
      isFontSizeMixed: () => false,
      getFontFamily: () => null,
      isFontFamilyMixed: () => false,
      getFontFaces: () => [],
      getFontColor: () => null,
      isFontColorMixed: () => false,
      getHighlightColor: () => null,
      isHighlightColorMixed: () => false,
      getParagraphStyle: () => 'p' as const,
      isParagraphStyleMixed: () => false,
      isAlignLeft: () => false,
      isAlignCenter: () => false,
      isAlignRight: () => false,
      isAlignJustify: () => false,
      canOutdent: () => false,
      isBulletList: () => false,
      isNumberedList: () => false,
      customParagraphStylesEnabled: () => true,
      getCustomParagraphStyles: () => [
        {
          id: 'quote',
          name: 'Quote',
          font: {
            size: 12,
            unit: 'pt',
            marks: { bold: false, italic: true, underline: false, strikethrough: false },
            fontFamily: null,
            fontColor: null,
            highlightColor: null,
          },
        },
        {
          id: 'title',
          name: 'Title',
          font: {
            size: 22,
            unit: 'pt',
            marks: { bold: true, italic: false, underline: false, strikethrough: false },
            fontFamily: null,
            fontColor: '#1e3a5f',
            highlightColor: null,
          },
        },
      ],
      isCustomParagraphStylesLoading: () => false,
      isLink: () => false,
      isImageSelected: () => false,
      isInTable: () => false,
      hasTextSelection: () => true,
    },
  },
}
