import type { ToolbarCatalog } from '../../toolbar/types'
import {
  CellPropertiesIcon,
  RowPropertiesIcon,
  TableColumnIcon,
  TableIcon,
  TableRowIcon,
} from '../../icons'

export const tableCatalog: ToolbarCatalog = {
  menus: {},
  submenus: {
    insertRow: {
      id: 'insertRow',
      labelKey: 'menuInsertRow',
      ariaKey: 'menuInsertRowAria',
      enabled: 'isInTable',
    },
    insertColumn: {
      id: 'insertColumn',
      labelKey: 'menuInsertColumn',
      ariaKey: 'menuInsertColumnAria',
      enabled: 'isInTable',
    },
  },
  groups: {},
  items: {
    table: {
      id: 'table',
      command: 'openTableDialog',
      icon: TableIcon,
      labelKey: 'commandTable',
      ariaKey: 'commandTableAria',
      enabled: 'isVisualMode',
    },
    insertRowBelow: {
      id: 'insertRowBelow',
      command: 'insertRowBelow',
      icon: TableRowIcon,
      labelKey: 'commandInsertRowBelow',
      ariaKey: 'commandInsertRowBelowAria',
      enabled: 'isInTable',
    },
    insertRowBefore: {
      id: 'insertRowBefore',
      command: 'insertRowBefore',
      icon: TableRowIcon,
      labelKey: 'commandInsertRowBefore',
      ariaKey: 'commandInsertRowBeforeAria',
      enabled: 'isInTable',
    },
    deleteRow: {
      id: 'deleteRow',
      command: 'deleteRow',
      icon: TableRowIcon,
      labelKey: 'commandDeleteRow',
      ariaKey: 'commandDeleteRowAria',
      enabled: 'isInTable',
    },
    insertColumnAfter: {
      id: 'insertColumnAfter',
      command: 'insertColumnAfter',
      icon: TableColumnIcon,
      labelKey: 'commandInsertColumnAfter',
      ariaKey: 'commandInsertColumnAfterAria',
      enabled: 'isInTable',
    },
    insertColumnBefore: {
      id: 'insertColumnBefore',
      command: 'insertColumnBefore',
      icon: TableColumnIcon,
      labelKey: 'commandInsertColumnBefore',
      ariaKey: 'commandInsertColumnBeforeAria',
      enabled: 'isInTable',
    },
    deleteColumn: {
      id: 'deleteColumn',
      command: 'deleteColumn',
      icon: TableColumnIcon,
      labelKey: 'commandDeleteColumn',
      ariaKey: 'commandDeleteColumnAria',
      enabled: 'isInTable',
    },
    tableProperties: {
      id: 'tableProperties',
      command: 'openTableProperties',
      icon: TableIcon,
      labelKey: 'commandTableProperties',
      ariaKey: 'commandTablePropertiesAria',
      enabled: 'isInTable',
    },
    cellProperties: {
      id: 'cellProperties',
      command: 'openCellProperties',
      icon: CellPropertiesIcon,
      labelKey: 'commandCellProperties',
      ariaKey: 'commandCellPropertiesAria',
      enabled: 'isInTable',
    },
    rowProperties: {
      id: 'rowProperties',
      command: 'openRowProperties',
      icon: RowPropertiesIcon,
      labelKey: 'commandRowProperties',
      ariaKey: 'commandRowPropertiesAria',
      enabled: 'isInTable',
    },
  },
}
