import { MENU_SEPARATOR, type ToolbarLayout } from './types'

export const defaultToolbarLayout: ToolbarLayout = {
  menus: [
    { id: 'file', items: ['save', 'open', MENU_SEPARATOR, 'print'] },
    { id: 'edit', items: ['undo', 'redo', MENU_SEPARATOR, { submenu: 'page', items: ['pageProperties', MENU_SEPARATOR, 'deletePage'] }] },
    {
      id: 'view',
      items: [
        'visual',
        'html',
        MENU_SEPARATOR,
        {
          submenu: 'toolbar',
          items: [
            'customizeToolbar',
            MENU_SEPARATOR,
            {
              submenu: 'toolbarPosition',
              items: [
                'toolbarPositionTop',
                'toolbarPositionLeft',
                'toolbarPositionRight',
                'toolbarPositionBottom',
              ],
            },
          ],
        },
        MENU_SEPARATOR,
        {
          submenu: 'zoom',
          items: [
            'pageZoomFitWidth',
            'pageZoomFitPage',
            MENU_SEPARATOR,
            'pageZoom50',
            'pageZoom75',
            'pageZoom100',
            'pageZoom125',
            'pageZoom150',
            'pageZoom200',
          ],
        },
        MENU_SEPARATOR,
        'lightMode',
        'darkMode',
        MENU_SEPARATOR,
        'toggleCommentsVisible',
        'ruler',
        'preview',
        'readAloud',
        'fullscreen',
      ],
    },
    {
      id: 'insert',
      items: [
        'pageBreak',
        { submenu: 'insertPage', items: ['insertPageBefore', 'insertPageAfter'] },
        MENU_SEPARATOR,
        'table',
        MENU_SEPARATOR,
        'image',
        'pageBackgroundImage',
        'paragraphBackgroundImage',
        'audio',
        'youtube',
        'horizontalRule',
        MENU_SEPARATOR,
        'link',
        'bookmark',
        MENU_SEPARATOR,
        'insertComment',
      ],
    },
    {
      id: 'format',
      items: [
        { submenu: 'paragraphStyles', items: [] },
        MENU_SEPARATOR,
        {
          submenu: 'font',
          items: [
            'fontProperties',
            'customCss',
            MENU_SEPARATOR,
            { submenu: 'highlightColor', items: [] },
            MENU_SEPARATOR,
            'bold',
            'italic',
            'underline',
            'strikethrough',
          ],
        },
        MENU_SEPARATOR,
        'clearFormatting',
        MENU_SEPARATOR,
        {
          submenu: 'paragraph',
          items: [
            'paragraphProperties',
            MENU_SEPARATOR,
            'alignLeft',
            'alignCenter',
            'alignRight',
            'alignJustify',
            MENU_SEPARATOR,
            'indent',
            'outdent',
            MENU_SEPARATOR,
            'bulletList',
            'numberedList',
          ],
        },
        MENU_SEPARATOR,
        'imageProperties',
      ],
    },
    {
      id: 'table',
      items: [
        'table',
        MENU_SEPARATOR,
        { submenu: 'insertRow', items: ['insertRowBefore', 'insertRowBelow', 'deleteRow'] },
        { submenu: 'insertColumn', items: ['insertColumnBefore', 'insertColumnAfter', 'deleteColumn'] },
        MENU_SEPARATOR,
        'mergeCells',
        'unmergeCells',
        MENU_SEPARATOR,
        'tableProperties',
        'rowProperties',
        'cellProperties',
      ],
    },
  ],
  iconGroups: [
    { id: 'file', items: ['save', 'open'] },
    { id: 'print', items: ['print'] },
    { id: 'edit', items: ['undo', 'redo'] },
    { id: 'insert', items: ['link', 'bookmark', 'image', 'table', 'horizontalRule', 'addComment'] },
    { id: 'table', items: ['mergeCells', 'unmergeCells'] },
    { id: 'font', items: ['fontFamily', 'paragraphStyle', 'fontSize', 'fontColor', 'highlightColor', 'customCss', 'formatBrush', 'bold', 'italic', 'underline', 'strikethrough', 'clearFormatting'] },
    { id: 'align', items: ['alignLeft', 'alignCenter', 'alignRight', 'alignJustify'] },
    { id: 'paragraph', items: ['indent', 'outdent', 'bulletList', 'numberedList'] },
    { id: 'view', items: ['visual', 'html', 'preview', 'readAloud', 'toggleCommentsVisible'] },
    { id: 'fullscreen', items: ['fullscreen'] },
  ],
}
