import { describe, expect, it, vi } from 'vitest'
import { createFileCommands } from './commands'
import { loadHtml, saveHtml } from './fileDialogs'
import { printHtml } from './printHtml'

vi.mock('./fileDialogs', () => ({
  saveHtml: vi.fn(async () => undefined),
  loadHtml: vi.fn(async () => null),
}))

vi.mock('./printHtml', () => ({
  printHtml: vi.fn(),
}))

describe('createFileCommands', () => {
  it('saves the current html', async () => {
    const setHtml = vi.fn()
    const commands = createFileCommands({
      getHtml: () => '<p>Doc</p>',
      setHtml,
      getMode: () => 'visual',
      setMode: vi.fn(),
      getFullscreen: () => false,
      setFullscreen: vi.fn(),
      getDarkMode: () => false,
      setDarkMode: vi.fn(),
      getToolbarPosition: () => 'top',
      setToolbarPosition: vi.fn(),
      openCustomizeToolbar: vi.fn(),
      openDocumentPreview: vi.fn(),
      toggleReadAloud: vi.fn(),
      isReadingAloud: () => false,
      canReadAloud: () => true,
      getSelection: () => ({ text: '', collapsed: true, start: 0, end: 0 }),
      insertText: vi.fn(),
      insertHtml: vi.fn(),
      undo: vi.fn(),
      redo: vi.fn(),
      canUndo: () => false,
      canRedo: () => false,
      toggleFontMark: vi.fn(),
      isFontMarkActive: () => false,
      setFontSize: vi.fn(),
      setFontSizeUnit: vi.fn(),
      getFontSize: () => null,
      getFontSizeUnit: () => 'pt',
      isFontSizeMixed: () => false,
      setFontFamily: vi.fn(),
      getFontFamily: () => null,
      isFontFamilyMixed: () => false,
      getFontFaces: () => [],
      setFontColor: vi.fn(),
    setHighlightColor: vi.fn(),
    getFontColor: () => null,
    isFontColorMixed: () => false,
    getHighlightColor: () => null,
    isHighlightColorMixed: () => false,
    setParagraphStyle: vi.fn(),
    getParagraphStyle: () => null,
    isParagraphStyleMixed: () => false,
    setTextAlign: vi.fn(),
    getTextAlign: () => null,
    isTextAlignMixed: () => false,
    indent: vi.fn(),
    outdent: vi.fn(),
    canOutdent: () => false,
    toggleList: vi.fn(),
    isBulletList: () => false,
    isNumberedList: () => false,
    openFontProperties: vi.fn(),
    applyFontProperties: vi.fn(),
    openCustomCss: vi.fn(),
    applyCustomCss: vi.fn(),
    openParagraphProperties: vi.fn(),
      applyParagraphProperties: vi.fn(),
      openPageProperties: vi.fn(),
      applyPageProperties: vi.fn(),
      openCustomParagraphStyleDialog: vi.fn(),
      applyCustomParagraphStyle: vi.fn(),
      customParagraphStylesEnabled: () => false,
      getCustomParagraphStyles: () => [],
      isCustomParagraphStylesLoading: () => false,
      openLinkDialog: vi.fn(),
      applyLink: vi.fn(),
      openBookmarkDialog: vi.fn(),
      applyBookmark: vi.fn(),
      openImageDialog: vi.fn(),
      applyImage: vi.fn(),
      openAudioDialog: vi.fn(),
      applyAudio: vi.fn(),
      openYoutubeDialog: vi.fn(),
      applyYoutube: vi.fn(),
      openImageProperties: vi.fn(),
      applyImageProperties: vi.fn(),
      insertHorizontalRule: vi.fn(),
    openTableDialog: vi.fn(),
    applyTable: vi.fn(),
    openTableProperties: vi.fn(),
    applyTableProperties: vi.fn(),
    openCellProperties: vi.fn(),
    applyCellProperties: vi.fn(),
    openRowProperties: vi.fn(),
    applyRowProperties: vi.fn(),
    insertRowBelow: vi.fn(),
    insertRowBefore: vi.fn(),
    deleteRow: vi.fn(),
    insertColumnAfter: vi.fn(),
    insertColumnBefore: vi.fn(),
    deleteColumn: vi.fn(),
    mergeCells: vi.fn(),
    unmergeCells: vi.fn(),
      cut: vi.fn(),
      copy: vi.fn(),
      deleteSelection: vi.fn(),
      clearFormatting: vi.fn(),
      toggleFormatBrush: vi.fn(),
      isLink: () => false,
      isImageSelected: () => false,
    isInTable: () => false,
    canMergeCells: () => false,
    canUnmergeCells: () => false,
    hasTextSelection: () => false,
    toggleFormatBrush: vi.fn(),
    isFormatBrushActive: () => false,
    })

    await commands.save()

    expect(saveHtml).toHaveBeenCalledWith('<p>Doc</p>')
    expect(setHtml).not.toHaveBeenCalled()
  })

  it('opens html into the editor', async () => {
    vi.mocked(loadHtml).mockResolvedValueOnce('<p>Loaded</p>')
    const setHtml = vi.fn()
    const commands = createFileCommands({
      getHtml: () => '',
      setHtml,
      getMode: () => 'visual',
      setMode: vi.fn(),
      getFullscreen: () => false,
      setFullscreen: vi.fn(),
      getDarkMode: () => false,
      setDarkMode: vi.fn(),
      getToolbarPosition: () => 'top',
      setToolbarPosition: vi.fn(),
      openCustomizeToolbar: vi.fn(),
      openDocumentPreview: vi.fn(),
      toggleReadAloud: vi.fn(),
      isReadingAloud: () => false,
      canReadAloud: () => true,
      getSelection: () => ({ text: '', collapsed: true, start: 0, end: 0 }),
      insertText: vi.fn(),
      insertHtml: vi.fn(),
      undo: vi.fn(),
      redo: vi.fn(),
      canUndo: () => false,
      canRedo: () => false,
      toggleFontMark: vi.fn(),
      isFontMarkActive: () => false,
      setFontSize: vi.fn(),
      setFontSizeUnit: vi.fn(),
      getFontSize: () => null,
      getFontSizeUnit: () => 'pt',
      isFontSizeMixed: () => false,
      setFontFamily: vi.fn(),
      getFontFamily: () => null,
      isFontFamilyMixed: () => false,
      getFontFaces: () => [],
      setFontColor: vi.fn(),
    setHighlightColor: vi.fn(),
    getFontColor: () => null,
    isFontColorMixed: () => false,
    getHighlightColor: () => null,
    isHighlightColorMixed: () => false,
    setParagraphStyle: vi.fn(),
    getParagraphStyle: () => null,
    isParagraphStyleMixed: () => false,
    setTextAlign: vi.fn(),
    getTextAlign: () => null,
    isTextAlignMixed: () => false,
    indent: vi.fn(),
    outdent: vi.fn(),
    canOutdent: () => false,
    toggleList: vi.fn(),
    isBulletList: () => false,
    isNumberedList: () => false,
    openFontProperties: vi.fn(),
    applyFontProperties: vi.fn(),
    openCustomCss: vi.fn(),
    applyCustomCss: vi.fn(),
    openParagraphProperties: vi.fn(),
      applyParagraphProperties: vi.fn(),
      openPageProperties: vi.fn(),
      applyPageProperties: vi.fn(),
      openCustomParagraphStyleDialog: vi.fn(),
      applyCustomParagraphStyle: vi.fn(),
      customParagraphStylesEnabled: () => false,
      getCustomParagraphStyles: () => [],
      isCustomParagraphStylesLoading: () => false,
      openLinkDialog: vi.fn(),
      applyLink: vi.fn(),
      openBookmarkDialog: vi.fn(),
      applyBookmark: vi.fn(),
      openImageDialog: vi.fn(),
      applyImage: vi.fn(),
      openAudioDialog: vi.fn(),
      applyAudio: vi.fn(),
      openYoutubeDialog: vi.fn(),
      applyYoutube: vi.fn(),
      openImageProperties: vi.fn(),
      applyImageProperties: vi.fn(),
      insertHorizontalRule: vi.fn(),
    openTableDialog: vi.fn(),
    applyTable: vi.fn(),
    openTableProperties: vi.fn(),
    applyTableProperties: vi.fn(),
    openCellProperties: vi.fn(),
    applyCellProperties: vi.fn(),
    openRowProperties: vi.fn(),
    applyRowProperties: vi.fn(),
    insertRowBelow: vi.fn(),
    insertRowBefore: vi.fn(),
    deleteRow: vi.fn(),
    insertColumnAfter: vi.fn(),
    insertColumnBefore: vi.fn(),
    deleteColumn: vi.fn(),
    mergeCells: vi.fn(),
    unmergeCells: vi.fn(),
      cut: vi.fn(),
      copy: vi.fn(),
      deleteSelection: vi.fn(),
      clearFormatting: vi.fn(),
      toggleFormatBrush: vi.fn(),
      isLink: () => false,
      isImageSelected: () => false,
    isInTable: () => false,
    canMergeCells: () => false,
    canUnmergeCells: () => false,
    hasTextSelection: () => false,
    toggleFormatBrush: vi.fn(),
    isFormatBrushActive: () => false,
    })

    await commands.open()

    expect(setHtml).toHaveBeenCalledWith('<p>Loaded</p>')
  })

  it('does not replace html when open is cancelled', async () => {
    vi.mocked(loadHtml).mockResolvedValueOnce(null)
    const setHtml = vi.fn()
    const commands = createFileCommands({
      getHtml: () => '<p>Keep</p>',
      setHtml,
      getMode: () => 'visual',
      setMode: vi.fn(),
      getFullscreen: () => false,
      setFullscreen: vi.fn(),
      getDarkMode: () => false,
      setDarkMode: vi.fn(),
      getToolbarPosition: () => 'top',
      setToolbarPosition: vi.fn(),
      openCustomizeToolbar: vi.fn(),
      openDocumentPreview: vi.fn(),
      toggleReadAloud: vi.fn(),
      isReadingAloud: () => false,
      canReadAloud: () => true,
      getSelection: () => ({ text: '', collapsed: true, start: 0, end: 0 }),
      insertText: vi.fn(),
      insertHtml: vi.fn(),
      undo: vi.fn(),
      redo: vi.fn(),
      canUndo: () => false,
      canRedo: () => false,
      toggleFontMark: vi.fn(),
      isFontMarkActive: () => false,
      setFontSize: vi.fn(),
      setFontSizeUnit: vi.fn(),
      getFontSize: () => null,
      getFontSizeUnit: () => 'pt',
      isFontSizeMixed: () => false,
      setFontFamily: vi.fn(),
      getFontFamily: () => null,
      isFontFamilyMixed: () => false,
      getFontFaces: () => [],
      setFontColor: vi.fn(),
    setHighlightColor: vi.fn(),
    getFontColor: () => null,
    isFontColorMixed: () => false,
    getHighlightColor: () => null,
    isHighlightColorMixed: () => false,
    setParagraphStyle: vi.fn(),
    getParagraphStyle: () => null,
    isParagraphStyleMixed: () => false,
    setTextAlign: vi.fn(),
    getTextAlign: () => null,
    isTextAlignMixed: () => false,
    indent: vi.fn(),
    outdent: vi.fn(),
    canOutdent: () => false,
    toggleList: vi.fn(),
    isBulletList: () => false,
    isNumberedList: () => false,
    openFontProperties: vi.fn(),
    applyFontProperties: vi.fn(),
    openCustomCss: vi.fn(),
    applyCustomCss: vi.fn(),
    openParagraphProperties: vi.fn(),
      applyParagraphProperties: vi.fn(),
      openPageProperties: vi.fn(),
      applyPageProperties: vi.fn(),
      openCustomParagraphStyleDialog: vi.fn(),
      applyCustomParagraphStyle: vi.fn(),
      customParagraphStylesEnabled: () => false,
      getCustomParagraphStyles: () => [],
      isCustomParagraphStylesLoading: () => false,
      openLinkDialog: vi.fn(),
      applyLink: vi.fn(),
      openBookmarkDialog: vi.fn(),
      applyBookmark: vi.fn(),
      openImageDialog: vi.fn(),
      applyImage: vi.fn(),
      openAudioDialog: vi.fn(),
      applyAudio: vi.fn(),
      openYoutubeDialog: vi.fn(),
      applyYoutube: vi.fn(),
      openImageProperties: vi.fn(),
      applyImageProperties: vi.fn(),
      insertHorizontalRule: vi.fn(),
    openTableDialog: vi.fn(),
    applyTable: vi.fn(),
    openTableProperties: vi.fn(),
    applyTableProperties: vi.fn(),
    openCellProperties: vi.fn(),
    applyCellProperties: vi.fn(),
    openRowProperties: vi.fn(),
    applyRowProperties: vi.fn(),
    insertRowBelow: vi.fn(),
    insertRowBefore: vi.fn(),
    deleteRow: vi.fn(),
    insertColumnAfter: vi.fn(),
    insertColumnBefore: vi.fn(),
    deleteColumn: vi.fn(),
    mergeCells: vi.fn(),
    unmergeCells: vi.fn(),
      cut: vi.fn(),
      copy: vi.fn(),
      deleteSelection: vi.fn(),
      clearFormatting: vi.fn(),
      toggleFormatBrush: vi.fn(),
      isLink: () => false,
      isImageSelected: () => false,
    isInTable: () => false,
    canMergeCells: () => false,
    canUnmergeCells: () => false,
    hasTextSelection: () => false,
    toggleFormatBrush: vi.fn(),
    isFormatBrushActive: () => false,
    })

    await commands.open()

    expect(setHtml).not.toHaveBeenCalled()
  })

  it('prints the current html', () => {
    const setHtml = vi.fn()
    const commands = createFileCommands({
      getHtml: () => '<p>Doc</p>',
      setHtml,
      getMode: () => 'visual',
      setMode: vi.fn(),
      getFullscreen: () => false,
      setFullscreen: vi.fn(),
      getDarkMode: () => false,
      setDarkMode: vi.fn(),
      getToolbarPosition: () => 'top',
      setToolbarPosition: vi.fn(),
      openCustomizeToolbar: vi.fn(),
      openDocumentPreview: vi.fn(),
      toggleReadAloud: vi.fn(),
      isReadingAloud: () => false,
      canReadAloud: () => true,
      getSelection: () => ({ text: '', collapsed: true, start: 0, end: 0 }),
      insertText: vi.fn(),
      insertHtml: vi.fn(),
      undo: vi.fn(),
      redo: vi.fn(),
      canUndo: () => false,
      canRedo: () => false,
      toggleFontMark: vi.fn(),
      isFontMarkActive: () => false,
      setFontSize: vi.fn(),
      setFontSizeUnit: vi.fn(),
      getFontSize: () => null,
      getFontSizeUnit: () => 'pt',
      isFontSizeMixed: () => false,
      setFontFamily: vi.fn(),
      getFontFamily: () => null,
      isFontFamilyMixed: () => false,
      getFontFaces: () => [],
      setFontColor: vi.fn(),
      setHighlightColor: vi.fn(),
      getFontColor: () => null,
      isFontColorMixed: () => false,
      getHighlightColor: () => null,
      isHighlightColorMixed: () => false,
      setParagraphStyle: vi.fn(),
      getParagraphStyle: () => null,
      isParagraphStyleMixed: () => false,
      setTextAlign: vi.fn(),
      getTextAlign: () => null,
      isTextAlignMixed: () => false,
      indent: vi.fn(),
      outdent: vi.fn(),
      canOutdent: () => false,
      toggleList: vi.fn(),
      isBulletList: () => false,
      isNumberedList: () => false,
      openFontProperties: vi.fn(),
    applyFontProperties: vi.fn(),
    openCustomCss: vi.fn(),
    applyCustomCss: vi.fn(),
    openParagraphProperties: vi.fn(),
      applyParagraphProperties: vi.fn(),
      openPageProperties: vi.fn(),
      applyPageProperties: vi.fn(),
      openCustomParagraphStyleDialog: vi.fn(),
      applyCustomParagraphStyle: vi.fn(),
      customParagraphStylesEnabled: () => false,
      getCustomParagraphStyles: () => [],
      isCustomParagraphStylesLoading: () => false,
      openLinkDialog: vi.fn(),
      applyLink: vi.fn(),
      openBookmarkDialog: vi.fn(),
      applyBookmark: vi.fn(),
      openImageDialog: vi.fn(),
      applyImage: vi.fn(),
      openAudioDialog: vi.fn(),
      applyAudio: vi.fn(),
      openYoutubeDialog: vi.fn(),
      applyYoutube: vi.fn(),
      openImageProperties: vi.fn(),
      applyImageProperties: vi.fn(),
      insertHorizontalRule: vi.fn(),
    openTableDialog: vi.fn(),
    applyTable: vi.fn(),
    openTableProperties: vi.fn(),
    applyTableProperties: vi.fn(),
    openCellProperties: vi.fn(),
    applyCellProperties: vi.fn(),
    openRowProperties: vi.fn(),
    applyRowProperties: vi.fn(),
    insertRowBelow: vi.fn(),
    insertRowBefore: vi.fn(),
    deleteRow: vi.fn(),
    insertColumnAfter: vi.fn(),
    insertColumnBefore: vi.fn(),
    deleteColumn: vi.fn(),
    mergeCells: vi.fn(),
    unmergeCells: vi.fn(),
      cut: vi.fn(),
      copy: vi.fn(),
      deleteSelection: vi.fn(),
      clearFormatting: vi.fn(),
      toggleFormatBrush: vi.fn(),
      isLink: () => false,
      isImageSelected: () => false,
    isInTable: () => false,
    canMergeCells: () => false,
    canUnmergeCells: () => false,
    hasTextSelection: () => false,
    toggleFormatBrush: vi.fn(),
    isFormatBrushActive: () => false,
    })

    commands.print()

    expect(printHtml).toHaveBeenCalledWith('<p>Doc</p>')
    expect(setHtml).not.toHaveBeenCalled()
  })
})
