import type { ToolbarCatalog } from '../../toolbar/types'
import {
  CustomizeToolbarIcon,
  DarkModeIcon,
  FullscreenIcon,
  HtmlIcon,
  LightModeIcon,
  PreviewIcon,
  ReadAloudIcon,
  RulerIcon,
  VisualIcon,
} from '../../icons'

export const viewCatalog: ToolbarCatalog = {
  menus: {
    view: {
      id: 'view',
      labelKey: 'menuView',
      ariaKey: 'menuViewAria',
    },
  },
  submenus: {
    toolbar: {
      id: 'toolbar',
      labelKey: 'menuToolbar',
      ariaKey: 'menuToolbarAria',
    },
    toolbarPosition: {
      id: 'toolbarPosition',
      labelKey: 'menuToolbarPosition',
      ariaKey: 'menuToolbarPositionAria',
    },
    zoom: {
      id: 'zoom',
      labelKey: 'menuZoom',
      ariaKey: 'menuZoomAria',
    },
  },
  groups: {
    view: {
      id: 'view',
      labelKey: 'toolbarGroupView',
    },
    fullscreen: {
      id: 'fullscreen',
      labelKey: 'toolbarGroupFullscreen',
    },
  },
  items: {
    visual: {
      id: 'visual',
      command: 'setVisualMode',
      icon: VisualIcon,
      labelKey: 'modeVisual',
      ariaKey: 'modeVisualAria',
      active: 'isVisualMode',
    },
    html: {
      id: 'html',
      command: 'setHtmlMode',
      icon: HtmlIcon,
      labelKey: 'modeHtml',
      ariaKey: 'modeHtmlAria',
      active: 'isHtmlMode',
    },
    customizeToolbar: {
      id: 'customizeToolbar',
      command: 'openCustomizeToolbar',
      icon: CustomizeToolbarIcon,
      labelKey: 'commandCustomizeToolbar',
      ariaKey: 'commandCustomizeToolbarAria',
    },
    toolbarPositionTop: {
      id: 'toolbarPositionTop',
      command: 'setToolbarPositionTop',
      labelKey: 'toolbarPositionTop',
      ariaKey: 'toolbarPositionTopAria',
      active: 'isToolbarPositionTop',
    },
    toolbarPositionLeft: {
      id: 'toolbarPositionLeft',
      command: 'setToolbarPositionLeft',
      labelKey: 'toolbarPositionLeft',
      ariaKey: 'toolbarPositionLeftAria',
      active: 'isToolbarPositionLeft',
    },
    toolbarPositionRight: {
      id: 'toolbarPositionRight',
      command: 'setToolbarPositionRight',
      labelKey: 'toolbarPositionRight',
      ariaKey: 'toolbarPositionRightAria',
      active: 'isToolbarPositionRight',
    },
    toolbarPositionBottom: {
      id: 'toolbarPositionBottom',
      command: 'setToolbarPositionBottom',
      labelKey: 'toolbarPositionBottom',
      ariaKey: 'toolbarPositionBottomAria',
      active: 'isToolbarPositionBottom',
    },
    lightMode: {
      id: 'lightMode',
      command: 'setLightMode',
      icon: LightModeIcon,
      labelKey: 'modeLight',
      ariaKey: 'modeLightAria',
      active: 'isLightMode',
    },
    darkMode: {
      id: 'darkMode',
      command: 'setDarkMode',
      icon: DarkModeIcon,
      labelKey: 'modeDark',
      ariaKey: 'modeDarkAria',
      active: 'isDarkMode',
    },
    pageZoomFitWidth: {
      id: 'pageZoomFitWidth',
      command: 'setPageZoomFitWidth',
      labelKey: 'pageZoomFitWidth',
      ariaKey: 'pageZoomFitWidthAria',
      active: 'isPageZoomFitWidth',
    },
    pageZoomFitPage: {
      id: 'pageZoomFitPage',
      command: 'setPageZoomFitPage',
      labelKey: 'pageZoomFitPage',
      ariaKey: 'pageZoomFitPageAria',
      active: 'isPageZoomFitPage',
    },
    pageZoom50: {
      id: 'pageZoom50',
      command: 'setPageZoom50',
      labelKey: 'pageZoom50',
      ariaKey: 'pageZoom50Aria',
      active: 'isPageZoom50',
    },
    pageZoom75: {
      id: 'pageZoom75',
      command: 'setPageZoom75',
      labelKey: 'pageZoom75',
      ariaKey: 'pageZoom75Aria',
      active: 'isPageZoom75',
    },
    pageZoom100: {
      id: 'pageZoom100',
      command: 'setPageZoom100',
      labelKey: 'pageZoom100',
      ariaKey: 'pageZoom100Aria',
      active: 'isPageZoom100',
    },
    pageZoom125: {
      id: 'pageZoom125',
      command: 'setPageZoom125',
      labelKey: 'pageZoom125',
      ariaKey: 'pageZoom125Aria',
      active: 'isPageZoom125',
    },
    pageZoom150: {
      id: 'pageZoom150',
      command: 'setPageZoom150',
      labelKey: 'pageZoom150',
      ariaKey: 'pageZoom150Aria',
      active: 'isPageZoom150',
    },
    pageZoom200: {
      id: 'pageZoom200',
      command: 'setPageZoom200',
      labelKey: 'pageZoom200',
      ariaKey: 'pageZoom200Aria',
      active: 'isPageZoom200',
    },
    preview: {
      id: 'preview',
      command: 'openDocumentPreview',
      icon: PreviewIcon,
      labelKey: 'commandPreview',
      ariaKey: 'commandPreviewAria',
    },
    ruler: {
      id: 'ruler',
      command: 'toggleRuler',
      icon: RulerIcon,
      labelKey: 'commandRuler',
      ariaKey: 'commandRulerAria',
      active: 'isRulerVisible',
      toggle: true,
    },
    readAloud: {
      id: 'readAloud',
      command: 'toggleReadAloud',
      icon: ReadAloudIcon,
      labelKey: 'commandReadAloud',
      ariaKey: 'commandReadAloudAria',
      active: 'isReadingAloud',
      toggle: true,
      enabled: 'canReadAloud',
    },
    fullscreen: {
      id: 'fullscreen',
      command: 'toggleFullscreen',
      icon: FullscreenIcon,
      labelKey: 'modeFullscreen',
      ariaKey: 'modeFullscreenAria',
      active: 'isFullscreen',
      toggle: true,
    },
  },
}
